# Generated by Django 2.2.10 on 2020-04-07 01:06

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='cpf',
            field=models.CharField(max_length=11, validators=[core.validators.valid_cpf_format]),
        ),
    ]
