# Generated by Django 2.2.10 on 2020-05-26 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200526_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='title',
            new_name='name',
        ),
    ]
